# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  packagetracker:
    image: packagetracker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 44301:44301
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
